import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const artifacts=resolve(process.env.FINANCE_BROWSER_ARTIFACTS || '.local-data/wp-fin-003-browser');mkdirSync(artifacts,{recursive:true});
const browser=await chromium.launch({channel:process.env.FINANCE_BROWSER_CHANNEL || 'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
const url=process.env.FINANCE_BROWSER_URL || 'http://127.0.0.1:5187';
const pass=name=>{checks.push(name);console.log('PASS '+name)};
const row=description=>page.locator('tbody tr').filter({hasText:description});
const dialog=()=>page.getByRole('dialog');
const label=(text)=>dialog().getByLabel(text,{exact:true});
async function selectedText(locator){return locator.locator('option:checked').innerText()}
async function close(){await dialog().getByRole('button',{name:'Cerrar',exact:true}).click();await dialog().waitFor({state:'hidden'})}
try{
 await page.goto(url+'/?neutral',{waitUntil:'networkidle'});
 for(const description of ['Compra sintética','Entrada sintética']){
  await row(description).getByRole('button',{name:'Editar clasificación',exact:true}).click();assert.equal(await label('Tipo económico').inputValue(),'UNCLASSIFIED');assert(await label('Subcategoría').isDisabled());
  assert.equal(await label('Tipo económico').locator('option[value="INTERNAL_TRANSFER"]').count(),0);await close();
 }
 pass('Positive and negative movements open neutral; subcategory disabled; no generic transfer option');
 const groups=page.getByRole('group',{name:/Acciones de/});
 for(let i=0;i<await groups.count();i++){const g=groups.nth(i);assert.equal(await g.evaluate(e=>getComputedStyle(e).flexWrap),'nowrap');const boxes=await g.locator('button').evaluateAll(es=>es.map(e=>({y:e.getBoundingClientRect().y,w:e.getBoundingClientRect().width,label:e.getAttribute('aria-label'),title:e.title})));assert.equal(new Set(boxes.map(x=>x.y)).size,1);assert(boxes.every(x=>x.w>=32&&x.label&&x.title));}
 assert(await row('Compra sintética').getByRole('button',{name:'Clasifica primero el movimiento para crear una regla',exact:true}).isDisabled());pass('One-line desktop icons with accessible disabled reasons');
 await row('Compra sintética').getByRole('button',{name:'Editar clasificación',exact:true}).click();
 await label('Nota opcional').fill('Nota que debe permanecer');await label('Tipo económico').selectOption('OTHER_NON_OPERATING');
 await label('Categoría').selectOption('food');assert.deepEqual(await label('Subcategoría').locator('option').allTextContents(),['Sin subcategoría','Frescos']);await label('Subcategoría').selectOption('fresh');await label('Categoría').selectOption('sales');assert.equal(await label('Subcategoría').inputValue(),'');assert(!(await label('Subcategoría').innerText()).includes('Frescos'));
 for(const [button,input,name,select] of [['+ Categoría','Nombre de categoría','Categoría nueva','Categoría'],['+ Subcategoría','Nombre de subcategoría','Subcategoría nueva','Subcategoría'],['+ Proveedor / contraparte','Nombre de proveedor / contraparte','Proveedor nuevo','Proveedor / contraparte']]){
  const previousCategory=await label('Categoría').inputValue();const previousSub=await label('Subcategoría').inputValue();
  await dialog().getByRole('button',{name:button,exact:true}).click();await label(input).fill(name);await dialog().getByRole('button',{name:'Crear y seleccionar',exact:true}).click();await label(input).waitFor({state:'hidden'});
  assert.equal(await selectedText(label(select)),name);assert.equal(await label('Nota opcional').inputValue(),'Nota que debe permanecer');assert.equal(await label('Tipo económico').inputValue(),'OTHER_NON_OPERATING');
  if(select!=='Categoría')assert.equal(await label('Categoría').inputValue(),previousCategory);if(select==='Proveedor / contraparte')assert.equal(await label('Subcategoría').inputValue(),previousSub);
 }
 await label('Tipo económico').selectOption('OPERATING_EXPENSE');await dialog().getByRole('button',{name:'Confirmar clasificación',exact:true}).click();await dialog().waitFor({state:'hidden'});pass('Quick-create three catalogs preserves draft and selects each new entry');
 await row('Compra sintética').getByRole('button',{name:'Crear regla desde ejemplo confirmado',exact:true}).click();
 assert.equal(await label('Cuando la descripción contenga').inputValue(),'Compra sintética');assert.equal(await label('Cuenta de origen').inputValue(),'a');assert.equal(await label('Signo bancario').inputValue(),'NEGATIVE');assert.equal(await label('Tipo económico').inputValue(),'OPERATING_EXPENSE');assert.equal(await selectedText(label('Categoría')),'Categoría nueva');assert.equal(await selectedText(label('Subcategoría')),'Subcategoría nueva');assert.equal(await selectedText(label('Proveedor / contraparte')),'Proveedor nuevo');await label('Cuando la descripción contenga').fill('Compra');await dialog().getByRole('button',{name:'Guardar regla',exact:true}).click();await dialog().getByRole('button',{name:'Desactivar',exact:true}).waitFor();await close();pass('Rule prefill follows confirmed classification; rule creation requires explicit save');
 await row('Entrada sintética').getByRole('button',{name:'Editar clasificación',exact:true}).click();assert.equal(await label('Tipo económico').inputValue(),'UNCLASSIFIED');await label('Tipo económico').selectOption('FINANCING_INFLOW');await dialog().getByRole('button',{name:'Confirmar clasificación',exact:true}).click();await dialog().waitFor({state:'hidden'});pass('Compact row opens explicit classification without redundant inline controls');
 await page.getByRole('button',{name:'Cuentas y categorías',exact:true}).click();
 for(const [section,names] of [['Categorías',['Cat uno','Cat dos']],['Subcategorías',['Sub uno','Sub dos']],['Proveedores / contrapartes',['Proveedor uno','Proveedor dos']],['Cuentas',['Cuenta uno','Tarjeta dos']]]){
  await dialog().getByRole('button',{name:section,exact:true}).click();
  for(const name of names){await label('Nombre').fill(name);if(section==='Subcategorías')await label('Categoría').selectOption('food');if(section==='Cuentas'){await label('Últimos cuatro dígitos').fill('9999');if(name==='Tarjeta dos')await label('Producto').selectOption('CARD');}await dialog().getByRole('button',{name:'Guardar',exact:true}).click();await label('Nombre').waitFor();await page.waitForFunction(()=>document.querySelector('[role="dialog"] input')?.value==='');assert.equal(await dialog().count(),1);await dialog().getByText(name,{exact:true}).waitFor();}
  const li=dialog().locator('li').filter({hasText:names[0]});await li.getByRole('button',{name:'Editar',exact:true}).click();await label('Nombre').fill(names[0]+' editado');
  if(section==='Cuentas'){assert(await label('Banco').isDisabled());assert(await label('Producto').isDisabled());await label('Últimos cuatro dígitos').fill('4321');await dialog().getByRole('checkbox').uncheck();}
  if(section==='Subcategorías')assert(await label('Categoría').isDisabled());
  await dialog().getByRole('button',{name:'Guardar',exact:true}).click();await dialog().getByText(names[0]+' editado',{exact:true}).waitFor();
  if(section==='Cuentas'){const edited=dialog().locator('li').filter({hasText:names[0]+' editado'});assert((await edited.innerText()).includes('Inactiva'));await edited.getByRole('button',{name:'Editar',exact:true}).click();await dialog().getByRole('checkbox').check();await dialog().getByRole('button',{name:'Guardar',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[role="dialog"] input')?.value==='');}
 }
 assert.equal(await dialog().getByRole('button',{name:/Eliminar|Borrar/}).count(),0);await close();pass('Catalog stays open for repeated create in all four sections and safe renames/account status edits');
 await row('Compra sintética').getByRole('button',{name:'Dividir en asignaciones',exact:true}).click();assert((await dialog().innerText()).includes('El movimiento bancario original no cambia.'));assert.equal(await label('Tipo económico').locator('option[value="INTERNAL_TRANSFER"]').count(),0);await label('Categoría').selectOption('food');await label('Subcategoría').selectOption('fresh');await label('Categoría').selectOption('sales');assert.equal(await label('Subcategoría').inputValue(),'');await label('Importe').fill('-10');assert(await dialog().getByRole('button',{name:'Confirmar split',exact:true}).isDisabled());await dialog().getByRole('button',{name:'+ Añadir línea',exact:true}).click();assert.equal(await dialog().getByLabel('Tipo económico',{exact:true}).nth(1).inputValue(),'UNCLASSIFIED');assert.equal(await dialog().getByLabel('Importe',{exact:true}).nth(1).inputValue(),'-8.50');await dialog().getByRole('button',{name:'Confirmar split',exact:true}).click();await dialog().waitFor({state:'hidden'});pass('Split preserves exact cents, neutral new line and catalog dependency');
 await page.getByRole('button',{name:'Resumen',exact:true}).click();await page.getByRole('heading',{name:'Resumen bancario',exact:true}).waitFor();await page.screenshot({path:resolve(artifacts,'summary-partial.png'),fullPage:true});
 await page.goto(url+'/?summary&neutral',{waitUntil:'networkidle'});await page.getByRole('heading',{name:'3 movimientos pendientes de interpretación económica',exact:true}).waitFor();assert.equal(await page.getByText('Ingresos operativos',{exact:true}).count(),0);assert.equal(await page.getByText('Otros flujos confirmados',{exact:true}).count(),0);await page.screenshot({path:resolve(artifacts,'summary-neutral.png'),fullPage:true});await page.getByRole('button',{name:'Revisar movimientos',exact:true}).click();await row('Compra sintética').waitFor();pass('Dedicated summary prioritizes one attention state with no zero-card overload; review CTA works');
 await page.goto(url,{waitUntil:'networkidle'});await row('Sugerencia sintética').getByRole('button',{name:'Editar clasificación',exact:true}).click();assert.equal(await label('Tipo económico').inputValue(),'OPERATING_EXPENSE');assert((await dialog().innerText()).includes('Sugerencia pendiente de revisión'));await close();
 const filters=page.getByRole('region',{name:'Filtros de movimientos'});
 for(const [name,value,expected] of [['Cuenta','b','Entrada sintética'],['Estado','SUGGESTED','Sugerencia sintética']]){await filters.getByLabel(name,{exact:true}).selectOption(value);assert.equal(await page.locator('tbody tr').count(),1);assert((await page.locator('tbody').innerText()).includes(expected));await filters.getByLabel(name,{exact:true}).selectOption('');}
 await filters.getByLabel('Mes',{exact:true}).fill('2026-05');assert.equal(await page.locator('tbody tr').count(),1);await filters.getByLabel('Mes',{exact:true}).fill('');await filters.getByLabel('Buscar movimientos',{exact:true}).fill('Compra');assert.equal(await page.locator('tbody tr').count(),1);await filters.getByLabel('Buscar movimientos',{exact:true}).fill('');
 await filters.locator('summary').click();for(const [name,value] of [['Tipo económico','OPERATING_EXPENSE'],['Categoría','food'],['Proveedor / contraparte','party']]){await filters.getByLabel(name,{exact:true}).selectOption(value);assert.equal(await page.locator('tbody tr').count(),1);await filters.getByLabel(name,{exact:true}).selectOption('');}
 await page.getByRole('button',{name:/^Sugeridas · revisar/}).click();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Revisar selección (1)',exact:true}).waitFor();await filters.getByLabel('Mes',{exact:true}).fill('2026-04');assert(await page.getByRole('button',{name:'Revisar selección (0)',exact:true}).isDisabled());assert.equal((await page.evaluate(()=>window.financeCalls)).filter(c=>c[0]==='bulk').length,0);
 await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Revisar selección (1)',exact:true}).click();await dialog().getByRole('button',{name:'Confirmar explícitamente la selección',exact:true}).click();await dialog().waitFor({state:'hidden'});assert.equal((await page.evaluate(()=>window.financeCalls)).filter(c=>c[0]==='bulk').length,1);pass('All operational filters work; changing filters clears bulk selection; suggestions require explicit confirmation');
 await page.getByRole('button',{name:'Ver todas / limpiar',exact:true}).click();await page.screenshot({path:resolve(artifacts,'desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('table').evaluate(e=>e.parentElement.scrollWidth>e.parentElement.clientWidth));await page.setViewportSize({width:1280,height:900});
 // Auth context can change externally while a dialog is open; simulate that event, not a pointer through its backdrop.
 await row('Compra sintética').getByRole('button',{name:'Editar clasificación',exact:true}).click();await page.getByRole('button',{name:'Cambiar organización sintética',exact:true}).evaluate(button=>button.click());await dialog().waitFor({state:'hidden'});assert(!(await page.locator('tbody').innerText()).includes('Compra sintética'));pass('Small viewport uses contained table scrolling; organization change discards prior tenant editors');
 assert.deepEqual(errors,[]);writeFileSync(resolve(artifacts,'evidence.json'),JSON.stringify({status:'PASS',synthetic:true,hosted:false,viewport:{width:1280,height:900},checks,consoleErrors:errors},null,2));console.log('Finance synthetic browser regression PASS');
}catch(error){await page.screenshot({path:resolve(artifacts,'failure.png'),fullPage:true});console.error(JSON.stringify({checks,errors,body:(await page.locator('body').innerText()).slice(0,2500)}));throw error;}
finally{await browser.close()}
