import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const artifacts=resolve(process.env.FINANCE_BROWSER_ARTIFACTS||'.local-data/wp-fin-004-browser');mkdirSync(artifacts,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!errors.includes(m.text()))errors.push(m.text())});
await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
const row=text=>page.locator('tbody tr').filter({hasText:text}),dialog=()=>page.getByRole('dialog'),label=name=>dialog().getByLabel(name,{exact:true});
const pass=name=>{checks.push(name);console.log('PASS '+name)};
const close=async()=>{await dialog().getByRole('button',{name:'Cerrar',exact:true}).click();await dialog().waitFor({state:'hidden'})};
try{
 await page.goto('http://127.0.0.1:5187/?dense',{waitUntil:'networkidle'});await row('Compra sintética').waitFor();
 assert.equal(await page.locator('tbody tr').count(),25);assert.equal(await page.getByRole('columnheader',{name:'Cuenta',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Clasificar en fila',exact:true}).count(),0);
 const summary=await page.getByTestId('filtered-banking-summary').innerText();assert(summary.includes('137 movimientos'));
 const first=await page.locator('tbody tr').first().innerText();await page.getByRole('button',{name:'Siguiente',exact:true}).click();assert.notEqual(await page.locator('tbody tr').first().innerText(),first);assert.equal(await page.getByTestId('filtered-banking-summary').innerText(),summary);
 for(const size of ['50','100','25']){await page.getByLabel('Filas por página').selectOption(size);assert.equal(await page.locator('tbody tr').count(),Number(size));assert((await page.getByRole('navigation',{name:'Paginación de movimientos'}).innerText()).includes('Página 1'));}
 await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByLabel('Buscar movimientos',{exact:true}).fill('SUMINISTROS OLIVA');assert.equal(await page.locator('tbody tr').count(),14);assert((await page.getByRole('navigation',{name:'Paginación de movimientos'}).innerText()).includes('Página 1 de 1'));await page.getByRole('button',{name:'Ver todas / limpiar',exact:true}).click();pass('25/50/100 pagination, filter-before-page, page reset, and full filtered totals invariant');
 await page.evaluate(()=>scrollTo(0,0));
 const density=await page.locator('tbody tr').evaluateAll(rows=>rows.filter(r=>{const rect=r.getBoundingClientRect();return rect.top>=0&&rect.bottom<=innerHeight}).length);assert(density>=12,'Expected at least 12 complete rows at 1280x900, got '+density);
 const actions=page.getByRole('group',{name:/Acciones de/}).first();assert.equal(await actions.evaluate(e=>getComputedStyle(e).flexWrap),'nowrap');assert.equal((await actions.innerText()).replace(/\s/g,''),'✏️⚙️✂️');assert((await page.locator('tbody tr').first().locator('td').nth(1).getAttribute('title')).includes('Cuenta sintética A'));
 assert((await page.getByRole('button',{name:'Transferencias posibles (1)',exact:true}).boundingBox()).y<(await page.locator('table').boundingBox()).y);await page.screenshot({path:resolve(artifacts,'dense-desktop.png'),fullPage:false});pass('Dense rows, literal icons, subtle account context, and transfer access above table');
 await page.getByRole('button',{name:'Transferencias posibles (1)',exact:true}).click();assert((await dialog().innerText()).includes('Sugerida'));assert(!(await dialog().innerText()).includes('SUGGESTED'));assert((await dialog().innerText()).includes('↔'));await dialog().getByRole('button',{name:'Rechazar',exact:true}).click();await dialog().getByText(/Rechazada/).waitFor();await close();pass('Compact Spanish transfer-pair review');
 await row('SUMINISTROS OLIVA 2222').getByRole('button',{name:'Editar clasificación',exact:true}).click();assert((await dialog().boundingBox()).width<=580);assert.equal(await label('Tipo económico').inputValue(),'UNCLASSIFIED');await dialog().getByText('Basado en 2 movimientos similares',{exact:true}).waitFor();await dialog().getByRole('button',{name:'Usar sugerencia',exact:true}).click();assert.equal(await label('Tipo económico').inputValue(),'OPERATING_EXPENSE');await dialog().getByRole('button',{name:'Guardar sugerencia sin confirmar',exact:true}).click();await dialog().waitFor({state:'hidden'});
 let calls=await page.evaluate(()=>window.financeCalls);assert.equal(calls.find(c=>c[0]==='classification')[1].status,'SUGGESTED');
 await row('SUMINISTROS OLIVA 2223').getByRole('button',{name:'Editar clasificación',exact:true}).click();await dialog().getByRole('button',{name:'Descartar en esta sesión',exact:true}).click();assert.equal(await dialog().getByText('Basado en 2 movimientos similares',{exact:true}).count(),0);await close();pass('Local evidence starts neutral; generated suggestion persists SUGGESTED; dismissal does not write');
 await page.locator('summary').filter({hasText:'Propuestas por historial'}).click();await page.getByRole('button',{name:'Crear regla para este grupo',exact:true}).first().click();await label('Cuando la descripción contenga').fill('SUMINISTROS OLIVA');assert((await dialog().innerText()).includes('11 movimientos pendientes coinciden'));await dialog().getByRole('button',{name:'Guardar regla',exact:true}).click();await dialog().getByRole('button',{name:'Desactivar',exact:true}).waitFor();await dialog().getByRole('button',{name:'Aplicar reglas a pendientes',exact:true}).click();await dialog().getByText('11 sugerencias aplicadas a pendientes',{exact:true}).waitFor();await close();
 calls=await page.evaluate(()=>window.financeCalls);assert.equal(calls.filter(c=>c[0]==='classification').length,1);assert.equal(calls.filter(c=>c[0]==='apply-rules').length,1);assert.equal(calls.filter(c=>c[0]==='bulk').length,0);
 await page.getByRole('button',{name:/^Sugeridas · revisar/}).click();await page.getByRole('checkbox').first().check();await page.getByRole('checkbox').nth(1).check();await page.getByRole('button',{name:'Revisar selección (2)',exact:true}).click();await dialog().getByRole('button',{name:'Confirmar explícitamente la selección',exact:true}).click();await dialog().waitFor({state:'hidden'});calls=await page.evaluate(()=>window.financeCalls);assert.equal(calls.filter(c=>c[0]==='bulk').length,1);pass('Rule preview and group suggestions use one apply RPC; explicit bulk review stays separate');
 await page.getByRole('button',{name:'Resumen',exact:true}).click();await page.getByRole('heading',{name:'Resumen bancario',exact:true}).waitFor();await page.getByRole('region',{name:'Cuentas y tarjetas'}).getByText(/SABADELL · Tarjeta/).waitFor();await page.screenshot({path:resolve(artifacts,'summary.png'),fullPage:true});
 await page.getByRole('button',{name:'Métricas',exact:true}).click();await page.getByRole('heading',{name:'Métricas',exact:true}).waitFor();await page.getByRole('img',{name:'Tendencia mensual de flujo bancario neto',exact:true}).waitFor();await page.getByRole('region',{name:'Concentración por proveedor / contraparte'}).waitFor();await page.screenshot({path:resolve(artifacts,'metrics.png'),fullPage:true});pass('Summary account/card distinction and accessible visual Métricas render');
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'Consolidado',exact:true}).click();await page.locator('tbody tr').first().waitFor();assert.equal(await page.locator('tbody tr').count(),25);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));pass('Mobile containment and bounded DOM rows');
 assert.deepEqual(errors,[]);writeFileSync(resolve(artifacts,'insights-evidence.json'),JSON.stringify({status:'PASS',hosted:false,synthetic:true,visibleDesktopRows:density,checks,errors},null,2));
}catch(e){await page.screenshot({path:resolve(artifacts,'failure.png'),fullPage:true});console.error(JSON.stringify({checks,errors:errors.slice(0,10),body:(await page.locator('body').innerText()).slice(0,2000)}));throw e}finally{await browser.close()}
