import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { adminSnapshot, adminMutate, inviteTenantUser, inspectPermissions } from '../../lib/tenantAdminService';
import { ACCESS_PRESETS, permissionGroup, explainPermission } from '../../application/tenancy/accessNavigation';

const modules = ['bancos','ventas','compras','inventario','produccion','escandallos','personal','reporting','prediccion','documentos','integraciones'];
export default function TenantAdministration({ platform = false }) {
  const { organizationId, can, platformCan } = useAuth();
  const allowed = platform ? platformCan('platform.tenants.provision') : ['membership.users.invite','membership.roles.assign','membership.users.remove','org.config.write'].some(c => can(c));
  return allowed ? <AdminWorkspace key={(platform ? 'platform' : organizationId) || 'none'} platform={platform} organizationId={organizationId} can={can} /> : <p role="alert">Administración no autorizada.</p>;
}
function AdminWorkspace({ platform, organizationId, can }) {
  const [org, setOrg] = useState(platform ? '' : organizationId);
  const [data, setData] = useState(null), [memberId, setMemberId] = useState(''), [unitId,setUnitId] = useState('');
  const [effective,setEffective] = useState([]);
  const [error,setError] = useState(''), [message,setMessage] = useState(''), [busy,setBusy] = useState(false);
  const [email,setEmail] = useState(''), [role,setRole] = useState('CONSULTANT'), [preset,setPreset] = useState('BANKS_IMPORT');
  const [newTenant,setNewTenant] = useState({name:'',code:'',trade_name:''});
  const load = useCallback(async () => { setData(await adminSnapshot(org,platform)); },[org,platform]);
  useEffect(()=>{let active=true;setData(null);adminSnapshot(org,platform).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[org,platform]);
  useEffect(()=>{let active=true;setEffective([]);if(memberId&&!platform)inspectPermissions(org,memberId,unitId).then(rows=>{if(active)setEffective(rows)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[org,memberId,unitId,platform,data]);
  async function run(action) { setBusy(true);setError('');setMessage('');try{await action();await load();setMessage('Cambio guardado y auditado.')}catch(e){setError(e.message)}finally{setBusy(false)} }
  const mutate=(action,payload)=>run(()=>adminMutate(action,org,payload));
  const member=data?.members.find(m=>m.id===memberId),tenant=data?.organizations.find(o=>o.id===org);
  const input='border rounded p-2 bg-white';
  const canAssign=!platform&&can('membership.roles.assign');
  return <div className="p-5 space-y-5 max-w-6xl text-sm"><h2 className="text-xl font-semibold">{platform?'Administración de plataforma':'Administración de organización'}</h2>
    <p>{platform?'Gestiona el ciclo de vida y la disponibilidad de módulos. Esta autoridad no permite acceder a datos operativos.':'Gestiona usuarios, capacidades y alcance de la organización activa.'}</p>
    {error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status" className="text-emerald-800">{message}</p>}
    {platform&&<><label className="block">Tenant<select className={input} value={org} onChange={e=>{setOrg(e.target.value);setMemberId('');setError('')}}><option value="">Seleccionar tenant</option>{data?.organizations.map(o=><option key={o.id} value={o.id}>{o.name} · {o.is_active?'Activo':'Inactivo'}</option>)}</select></label>
      <details><summary>Crear tenant</summary><form className="flex gap-2 flex-wrap p-3" onSubmit={e=>{e.preventDefault();run(async()=>{const r=await adminMutate('tenant.create',null,newTenant);setOrg(r.organization_id)})}}>{[['name','Nombre visible'],['code','Código único'],['trade_name','Nombre comercial / referencia']].map(([key,label])=><label key={key}>{label}<input required={key!=='trade_name'} className={'block '+input} value={newTenant[key]} onChange={e=>setNewTenant({...newTenant,[key]:e.target.value})}/></label>)}<button disabled={busy} className={input}>Crear tenant ES · EUR</button></form></details></>}
    {!data&&<p role="status">Cargando administración…</p>}
    {tenant&&<section className="bg-gray-50 rounded p-3"><h3 className="font-semibold">{tenant.name}</h3><p>{tenant.trade_name} · {tenant.country_code} · {tenant.currency} · {tenant.timezone}</p><p>{tenant.is_active?'Activo':'Inactivo'}</p>{platform&&<button disabled={busy} className={input} onClick={()=>mutate('tenant.active',{active:!tenant.is_active})}>{tenant.is_active?'Desactivar tenant':'Activar tenant'}</button>}</section>}
    {org&&data&&<>
      <section><h3 className="font-semibold">Módulos disponibles para la organización</h3><p className="text-gray-600">La habilitación del módulo no concede permisos al usuario.</p><div className="flex flex-wrap gap-3">{modules.map(key=><label key={key}><input type="checkbox" disabled={!platform||busy} checked={data.entitlements.some(e=>e.module_key===key&&e.is_enabled)} onChange={e=>mutate('entitlement.set',{module:key,enabled:e.target.checked})}/> {key}</label>)}</div></section>
      {(platform||(can('membership.users.invite')&&canAssign))&&<section><h3 className="font-semibold">Invitar usuario</h3><form className="flex gap-2 flex-wrap items-end" onSubmit={e=>{e.preventDefault();run(async()=>{await inviteTenantUser(org,email,role);setEmail('')})}}><label>Correo electrónico<input type="email" required className={'block '+input} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Rol inicial<select className={'block '+input} value={role} onChange={e=>setRole(e.target.value)}>{data.roles.map(r=><option key={r.id} value={r.code}>{r.name}</option>)}</select></label><button disabled={busy} className={input}>Enviar invitación segura</button></form><p className="text-gray-600">El destinatario configura su acceso mediante un enlace. Después puedes ajustar capacidades y alcance; no se muestran contraseñas.</p></section>}
      <section><h3 className="font-semibold">Usuarios y membresías</h3><select aria-label="Usuario a administrar" className={input} value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Seleccionar usuario</option>{data.members.map(m=><option key={m.id} value={m.id}>{m.display_name||m.user_id} · {m.role_code} · {m.is_active?'Activo':'Inactivo'}</option>)}</select></section>
      {member&&<section className="space-y-4 border rounded p-4"><h3 className="font-semibold">Acceso de {member.display_name||member.user_id}</h3>
        <label>Rol base <select disabled={!canAssign||busy} className={input} value={member.role_code} onChange={e=>mutate('member.role',{membership_id:member.id,role:e.target.value})}>{data.roles.map(r=><option key={r.id} value={r.code}>{r.name}</option>)}</select></label>
        {!platform&&can('membership.users.remove')&&<button className={'ml-3 '+input} disabled={busy} onClick={()=>mutate('member.active',{membership_id:member.id,active:!member.is_active})}>{member.is_active?'Desactivar membresía':'Activar membresía'}</button>}
        {canAssign&&<div className="flex gap-2"><select aria-label="Perfil de acceso" className={input} value={preset} onChange={e=>setPreset(e.target.value)}>{Object.entries(ACCESS_PRESETS).map(([key,p])=><option key={key} value={key}>{p.name}</option>)}</select><button disabled={busy} className={input} onClick={()=>mutate('member.preset',{membership_id:member.id,preset})}>Aplicar perfil y reemplazar excepciones</button></div>}
        <section><h4 className="font-semibold">Alcance operativo</h4><label><input type="checkbox" disabled={platform||!can('opunit.assign_scope')||busy} checked={member.is_organization_wide} onChange={e=>mutate('member.scope',{membership_id:member.id,organization_wide:e.target.checked,units:[]})}/> Toda la organización</label><div>{data.units.map(u=><label className="block" key={u.id}><input type="checkbox" disabled={platform||!can('opunit.assign_scope')||busy||member.is_organization_wide||!u.is_active} checked={data.scopes.some(s=>s.membership_id===member.id&&s.operational_unit_id===u.id)} onChange={e=>mutate('member.scope',{membership_id:member.id,organization_wide:false,units:e.target.checked?[...data.scopes.filter(s=>s.membership_id===member.id).map(s=>s.operational_unit_id),u.id]:data.scopes.filter(s=>s.membership_id===member.id&&s.operational_unit_id!==u.id).map(s=>s.operational_unit_id)})}/> {u.name}</label>)}</div></section>
        <label>Contexto de unidad para inspección <select className={input} value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Organización</option>{data.units.filter(u=>u.is_active).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>
        {[...new Set(data.capabilities.map(c=>permissionGroup(c.code)))].map(group=><details key={group} open={group==='Bancos'}><summary className="font-semibold cursor-pointer">{group}</summary><div className="divide-y">{data.capabilities.filter(c=>permissionGroup(c.code)===group).map(c=>{const override=data.overrides.find(o=>o.membership_id===member.id&&o.capability_id===c.id&&!o.operational_unit_id);return <div key={c.id} className="grid sm:grid-cols-3 gap-2 py-2"><span>{c.description||c.code}<details className="text-xs text-gray-500"><summary>Código avanzado</summary>{c.code}</details></span><span>{platform ? explainPermission(data,member,c,unitId||null) : effective.find(e=>e.code===c.code)?.allowed ? "Permitido · " + explainPermission(data,member,c,unitId||null) : "Denegado · " + explainPermission(data,member,c,unitId||null)}</span><select aria-label={'Permiso '+(c.description||c.code)} disabled={!canAssign||busy} className={input} value={override?.effect||'INHERIT'} onChange={e=>mutate('member.override',{membership_id:member.id,capability:c.code,effect:e.target.value})}><option value="INHERIT">Heredar rol</option><option value="GRANT">Conceder</option><option value="REVOKE">Denegar</option></select></div>})}</div></details>)}
      </section>}
      <details><summary>Auditoría de accesos</summary><ul>{data.audit.map(a=><li key={a.id}>{new Date(a.created_at).toLocaleString('es-ES')} · {a.action} · actor {a.actor}</li>)}</ul></details>
    </>}
  </div>;
}
