import { useMemo, useState } from 'react';
import { financeInsights, percentage } from '../../domains/finance/application/operationalInsights';
import { economicLabels } from '../../domains/finance/domain/economic';
export const currencyAmount = (cents, currency = 'EUR') => (cents / 100).toLocaleString('es-ES', { style: 'currency', currency });
export function BankingCards({ flow, currency = 'EUR' }) {
  return <div className="grid grid-cols-2 lg:grid-cols-4 gap-2 bg-gray-50 rounded-xl p-3">{[['Entradas bancarias brutas',flow.inflows],['Salidas bancarias brutas',flow.outflows],['Flujo bancario neto',flow.net],['Movimientos',flow.count]].map(([label,n],i)=><div key={label} className="px-2"><p className="text-xs text-gray-500">{label}</p><strong className="text-lg tabular-nums">{i===3?n:currencyAmount(n,currency)}</strong></div>)}</div>;
}
export function RankedBars({ title, rows, currency, limit = 8 }) {
  return <section aria-label={title} className="space-y-2 min-w-0"><h3 className="font-semibold text-sm">{title}</h3>{rows.length?rows.slice(0,limit).map(row=><div key={row.id} className="text-xs"><div className="flex justify-between gap-2"><span className="truncate" title={row.name}>{row.name}</span><span className="whitespace-nowrap">{currencyAmount(row.amount,currency)} · {row.percent.toFixed(1)}%</span></div><div className="h-2 rounded bg-gray-100 mt-1"><div className="h-2 rounded bg-emerald-600" style={{width:`${Math.min(100,row.percent)}%`}} /></div></div>):<p className="text-xs text-gray-500">Sin gastos operativos confirmados.</p>}<p className="text-xs text-gray-500">% de salidas operativas confirmadas, incluidos los importes sin asignación de catálogo. Reembolsos excluidos.</p></section>;
}
export function AccountAnalysis({ accounts, currency }) {
  return <section aria-label="Cuentas y tarjetas" className="space-y-2"><h3 className="text-sm font-semibold">Cuentas y tarjetas · flujo bancario</h3><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left text-gray-500"><th className="py-2">Banco / producto / cuenta</th><th className="text-right">Entradas</th><th className="text-right">Salidas</th><th className="text-right">Neto</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id} className="border-t border-gray-100"><td className="py-2 pr-2">{a.institution} · {a.product==='CARD'?'Tarjeta':a.product==='BANK_ACCOUNT'?'Cuenta':'Producto no informado'} · {a.name}</td><td className="text-right px-2 whitespace-nowrap">{currencyAmount(a.inflows,currency)}</td><td className="text-right px-2 whitespace-nowrap">{currencyAmount(a.outflows,currency)}</td><td className="text-right whitespace-nowrap">{currencyAmount(a.net,currency)}</td></tr>)}</tbody></table></div></section>;
}
function MonthChart({ months, currency }) {
  const rows=Object.entries(months).sort(([a],[b])=>a.localeCompare(b)),max=Math.max(1,...rows.flatMap(([,v])=>[v.inflows,v.outflows]));
  const minNet=Math.min(0,...rows.map(([,v])=>v.net)),maxNet=Math.max(1,...rows.map(([,v])=>v.net));
  const y=n=>110-(n-minNet)/(maxNet-minNet)*90,x=i=>rows.length<2?250:20+i*460/(rows.length-1);
  return <section aria-label="Flujo mensual" className="space-y-3"><h3 className="font-semibold text-sm">Entradas y salidas por mes</h3><p className="text-xs text-gray-500">Verde: entradas · rojo: salidas. Importes bancarios brutos.</p><div className="max-h-64 overflow-y-auto space-y-2">{rows.map(([month,v])=><div key={month} className="grid grid-cols-[4.5rem_1fr] gap-2 text-xs"><span>{month}</span><div><div className="flex items-center gap-2"><div className="h-2 bg-emerald-600 rounded" style={{width:`${v.inflows/max*70}%`}}/><span>{currencyAmount(v.inflows,currency)}</span></div><div className="flex items-center gap-2"><div className="h-2 bg-red-400 rounded" style={{width:`${v.outflows/max*70}%`}}/><span>{currencyAmount(v.outflows,currency)}</span></div></div></div>)}</div>
    <h4 className="text-sm font-semibold">Tendencia del flujo neto</h4><svg role="img" aria-label="Tendencia mensual de flujo bancario neto" viewBox="0 0 500 140" className="w-full max-h-40"><title>Flujo neto por mes; valores disponibles en la tabla inferior</title><line x1="15" x2="485" y1={y(0)} y2={y(0)} stroke="#d1d5db"/><polyline fill="none" stroke="#047857" strokeWidth="2" points={rows.map(([,v],i)=>`${x(i)},${y(v.net)}`).join(' ')}/>{rows.map(([month,v],i)=><circle key={month} cx={x(i)} cy={y(v.net)} r="3" fill="#047857"><title>{month}: {currencyAmount(v.net,currency)}</title></circle>)}</svg>
    <details className="text-xs"><summary className="cursor-pointer">Valores mensuales</summary><dl>{rows.map(([month,v])=><div key={month} className="flex justify-between"><dt>{month}</dt><dd>{currencyAmount(v.net,currency)}</dd></div>)}</dl></details>
  </section>;
}
export default function ExtractosGraficas({ movements = [] }) {
  const [month,setMonth]=useState(''),[currency,setCurrency]=useState('EUR');
  const filtered=useMemo(()=>movements.filter(m=>!month||m.fecha.startsWith(month)),[movements,month]);
  const data=useMemo(()=>financeInsights(filtered,currency),[filtered,currency]),m=data.metrics;
  const composition=Object.entries(m.economic).filter(([,v])=>v.count>0);
  return <div className="p-4 space-y-5"><header className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-semibold mr-auto">Métricas</h2><label className="text-sm">Mes <input aria-label="Mes" type="month" value={month} onChange={e=>setMonth(e.target.value)} className="border border-gray-200 rounded p-1"/></label><label className="text-sm">Moneda <select aria-label="Moneda" className="border border-gray-200 rounded p-1" value={currency} onChange={e=>setCurrency(e.target.value)}>{[...new Set(['EUR',...movements.map(m=>m.currency||'EUR')])].map(c=><option key={c}>{c}</option>)}</select></label></header>
    <BankingCards flow={m.banking} currency={currency}/>
    <div className="grid lg:grid-cols-2 gap-6"><MonthChart months={m.months} currency={currency}/><section aria-label="Composición económica" className="space-y-3"><h3 className="text-sm font-semibold">Interpretación del volumen de asignaciones</h3><p className="text-xs text-amber-900">{data.unresolvedPercent.toFixed(1)}% del volumen absoluto de asignaciones sigue sin interpretación confirmada ({currencyAmount(data.unresolvedVolume,currency)}).</p>{composition.map(([type,v])=><div key={type} className="text-xs"><div className="flex justify-between"><span>{economicLabels[type]}</span><span>{currencyAmount(v.inflows+v.outflows,currency)} · {percentage(v.inflows+v.outflows,data.allocationVolume).toFixed(1)}%</span></div><div className="h-2 bg-gray-100 rounded mt-1"><div className={'h-2 rounded '+(type==='UNCLASSIFIED'?'bg-amber-400':'bg-emerald-600')} style={{width:`${percentage(v.inflows+v.outflows,data.allocationVolume)}%`}}/></div></div>)}<p className="text-xs text-gray-500">Las sugerencias se incluyen en «Sin clasificar». Transferencias: ambos lados. Financiación y transferencias no son resultados operativos.</p></section></div>
    <section aria-label="Resultado operativo" className="text-sm bg-emerald-50 rounded-lg p-3">Confirmado: ingresos {currencyAmount(m.operatingIncome,currency)} · gastos netos {currencyAmount(m.operatingExpense,currency)} · resultado {currencyAmount(m.operatingIncome-m.operatingExpense,currency)}</section>
    <div className="grid lg:grid-cols-3 gap-6"><RankedBars title="Gasto por categoría" rows={data.categories} currency={currency}/><RankedBars title="Gasto por subcategoría" rows={data.subcategories} currency={currency}/><RankedBars title="Concentración por proveedor / contraparte" rows={data.providers} currency={currency}/></div>
    <AccountAnalysis accounts={data.accounts} currency={currency}/>
  </div>;
}
