import { useMemo, useState } from 'react';
import { financeInsights } from '../../domains/finance/application/operationalInsights';
import { economicLabels } from '../../domains/finance/domain/economic';
import { BankingCards, currencyAmount, RankedBars, AccountAnalysis } from './ExtractosGraficas';
export default function ExtractosResumen({ movements, onReview }) {
  const [currency,setCurrency]=useState('EUR');
  const data=useMemo(()=>financeInsights(movements,currency),[movements,currency]),m=data.metrics;
  const operating=m.economic.OPERATING_INCOME.count+m.economic.OPERATING_EXPENSE.count>0;
  const nonOperating=['INTERNAL_TRANSFER','FINANCING_INFLOW','FINANCING_OUTFLOW','CARD_SETTLEMENT','OTHER_NON_OPERATING'].filter(t=>m.economic[t].count);
  return <div className="p-4 space-y-4"><header className="flex items-center justify-between"><h2 className="text-lg font-semibold">Resumen bancario</h2><label className="text-sm">Moneda <select aria-label="Moneda" className="border border-gray-200 rounded p-1" value={currency} onChange={e=>setCurrency(e.target.value)}>{[...new Set(['EUR',...movements.map(m=>m.currency||'EUR')])].map(c=><option key={c}>{c}</option>)}</select></label></header>
    <BankingCards flow={m.banking} currency={currency}/>
    <section aria-label="Atención requerida" className={'rounded-lg p-3 '+(data.attention?'bg-amber-50':'bg-emerald-50')}><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{data.attention?`${data.attention} movimientos pendientes de interpretación económica`:m.banking.count?'Interpretación al día':'Todavía no hay movimientos'}</h3><button className="bg-emerald-700 text-white rounded px-3 py-1.5 text-sm" onClick={()=>onReview(currency)}>Revisar movimientos</button></div><p className="text-xs mt-2">Asignaciones: {m.pendingCount} pendientes · {m.suggestedCount} sugeridas · {data.confirmed} confirmadas con tipo · {m.unclassifiedCount} sin interpretación confirmada.</p><p className="text-xs">Por interpretar: {currencyAmount(data.unresolvedVolume,currency)} · {data.unresolvedPercent.toFixed(1)}% del volumen absoluto de asignaciones.</p></section>
    {operating?<section aria-label="Interpretación operativa" className="grid grid-cols-3 gap-2 text-sm">{[['Ingresos operativos',m.operatingIncome],['Gastos operativos',m.operatingExpense],['Resultado operativo',m.operatingIncome-m.operatingExpense]].map(([label,n])=><div key={label} className="p-2"><p className="text-xs text-gray-500">{label}</p><strong className="text-lg">{currencyAmount(n,currency)}</strong></div>)}</section>:<p className="text-xs text-gray-500">Aún no hay interpretación operativa confirmada. No se infiere a partir del signo bancario.</p>}
    {nonOperating.length>0&&<section aria-label="Interpretación no operativa" className="bg-gray-50 rounded-lg p-3"><h3 className="text-sm font-semibold mb-2">Otros flujos confirmados</h3><div className="flex flex-wrap gap-x-5 gap-y-2 text-xs">{nonOperating.map(t=><p key={t}>{economicLabels[t]}: <strong>{currencyAmount(m.economic[t].inflows+m.economic[t].outflows,currency)}</strong></p>)}</div><p className="text-xs text-gray-500 mt-1">Importes absolutos; transferencias incluyen ambos lados.</p></section>}
    {data.operatingOutflow>0&&<div className="grid lg:grid-cols-3 gap-5"><RankedBars title="Categorías principales" rows={data.categories} currency={currency} limit={3}/><RankedBars title="Subcategorías principales" rows={data.subcategories} currency={currency} limit={3}/><RankedBars title="Proveedores / contrapartes principales" rows={data.providers} currency={currency} limit={3}/></div>}
    {!!data.accounts.length&&<AccountAnalysis accounts={data.accounts} currency={currency}/>}<p className="text-xs text-gray-500">Consulta Métricas para la evolución y el análisis detallado.</p>
  </div>;
}
