import {describe,it,expect} from 'vitest';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {paginateMovements,normalizeFinanceDescription,buildConfirmedSimilarityIndex,findSimilarClassificationSuggestion,buildSuggestionGroups,financeInsights,previewRuleMatches} from '../../src/domains/finance/application/operationalInsights';
import {classificationInput,filterMovements,emptyFilters} from '../../src/modules/extractos/workflow';
import FinanceMovementRow from '../../src/modules/extractos/FinanceMovementRow';
import TransferReview from '../../src/modules/extractos/TransferReview';
import {readFileSync} from 'node:fs';
const org='synthetic-org';
const movement=(id,extra={},allocation={})=>({id,organization_id:org,fecha:'2026-01-01',status:'ACTIVE',currency:'EUR',monto:-10,descripcion:'Compra OLIVA MERCADO 12345',source_account_id:'a',source_account:{id:'a',name:'Bank A',institution:'BBVA',product_type:'BANK_ACCOUNT'},allocations:[{id:'alloc-'+id,monto:-10,economic_type:'OPERATING_EXPENSE',classification_status:'CONFIRMED',reconciliation_status:'UNMATCHED',category_id:'cat',subcategory_id:'sub',counterparty_id:'party',category:{name:'Food'},subcategory:{name:'Fresh'},counterparty:{name:'Oliva'},...allocation}],...extra});
const pending=(id='pending',extra={})=>movement(id,extra,{economic_type:'UNCLASSIFIED',classification_status:'PENDING',category_id:null,subcategory_id:null,counterparty_id:null});
const histories=[movement('one'),movement('two',{descripcion:'COMPRA  Oliva-Mercado 789'})];
describe('Operational pagination',()=>{
 const rows=Array.from({length:137},(_,i)=>pending(String(i),{source_account_id:i%2?'b':'a'}));
 it.each([25,50,100])('renders a bounded page of %s rows',size=>{const p=paginateMovements(rows,1,size);expect(p.rows).toHaveLength(size);expect(p.totalPages).toBe(Math.ceil(137/size));expect(p.total).toBe(137);});
 it('defaults to 25 and clamps invalid/last pages',()=>{expect(paginateMovements(rows).rows).toHaveLength(25);expect(paginateMovements(rows,99).page).toBe(6);expect(paginateMovements([],9).page).toBe(1);expect(paginateMovements(rows,-1,999).pageSize).toBe(25);});
 it('filters complete history before paging and preserves full filtered totals',()=>{const filtered=filterMovements(rows,{...emptyFilters(),account:'b'});const first=paginateMovements(filtered,1),second=paginateMovements(filtered,2);expect(first.total).toBe(68);expect(first.rows[0].id).toBe('1');expect(second.rows[0].id).toBe('51');expect(financeInsights(filtered).metrics.banking.outflows).toBe(68000);expect(financeInsights(first.rows).metrics.banking.outflows).toBe(25000);});
});
describe('Conservative deterministic history assistance',()=>{
 it('normalizes descriptions without determining meaning',()=>expect(normalizeFinanceDescription('  Olivá, mercado! ')).toBe('OLIVA MERCADO'));
 it('requires two confirmed examples and emits only SUGGESTED with explanation',()=>{const p=pending(),index=buildConfirmedSimilarityIndex(histories,org),s=findSimilarClassificationSuggestion(p,index,org);expect(s).toMatchObject({economic_type:'OPERATING_EXPENSE',classification_status:'SUGGESTED',count:2,explanation:'Basado en 2 movimientos similares'});expect(findSimilarClassificationSuggestion(p,buildConfirmedSimilarityIndex(histories.slice(0,1),org),org)).toBeNull();expect(classificationInput(org,p.allocations[0].id,s,'SUGGESTED').status).toBe('SUGGESTED');});
 it('recognizes recurring merchant text with varying references',()=>expect(findSimilarClassificationSuggestion(pending('p',{descripcion:'PAGO OLIVA MERCADO REF 888'}),buildConfirmedSimilarityIndex(histories,org),org)?.count).toBe(2));
 it('never suggests from sign alone or generic banking descriptions',()=>{const index=buildConfirmedSimilarityIndex(histories,org);expect(findSimilarClassificationSuggestion(pending('p',{descripcion:'OTRO COMERCIO'}),index,org)).toBeNull();expect(buildConfirmedSimilarityIndex(histories.map(m=>({...m,descripcion:'PAGO TARJETA 1234'})),org).size).toBe(0);});
 it.each(['economic_type','category_id','subcategory_id','counterparty_id'])('rejects historical conflict in %s',field=>{const changed=movement('conflict',{}, {[field]:field==='economic_type'?'FINANCING_OUTFLOW':'different'});expect(findSimilarClassificationSuggestion(pending(),buildConfirmedSimilarityIndex([...histories,changed],org),org)).toBeNull();});
 it('isolates tenant, account, currency, direction and existing counterparty',()=>{const index=buildConfirmedSimilarityIndex(histories,org);for(const extra of [{organization_id:'foreign'},{source_account_id:'b'},{currency:'USD'},{monto:10}])expect(findSimilarClassificationSuggestion(pending('p',extra),index,org)).toBeNull();const p=pending();p.allocations[0].counterparty_id='different';expect(findSimilarClassificationSuggestion(p,index,org)).toBeNull();expect(buildConfirmedSimilarityIndex(histories,'foreign').size).toBe(0);});
 it.each(['UNCLASSIFIED','INTERNAL_TRANSFER'])('never learns %s',type=>expect(buildConfirmedSimilarityIndex(histories.map(m=>({...m,allocations:[{...m.allocations[0],economic_type:type}]})),org).size).toBe(0));
 it('excludes suggestions, splits and linked history; dismissal is session-only',()=>{for(const a of [{classification_status:'SUGGESTED'},{transfer_candidate_id:'pair'}])expect(buildConfirmedSimilarityIndex(histories.map(m=>({...m,allocations:[{...m.allocations[0],...a}]})),org).size).toBe(0);expect(buildConfirmedSimilarityIndex(histories.map(m=>({...m,allocations:[m.allocations[0],m.allocations[0]]})),org).size).toBe(0);const index=buildConfirmedSimilarityIndex(histories,org);const rows=[pending('a'),pending('b')];expect([...buildSuggestionGroups(rows,index,org).groups.values()][0].ids.size).toBe(2);expect(buildSuggestionGroups(rows,index,org,new Set(['a'])).suggestions.size).toBe(1);expect(rows[0].allocations[0].classification_status).toBe('PENDING');});
 it('previews literal rule pattern, account, sign and pending unsplit eligibility',()=>{const rows=[...histories,pending('p'),pending('other',{source_account_id:'b'}),pending('positive',{monto:10})];expect(previewRuleMatches(rows,{pattern:'oliva',account:'a',sign:'NEGATIVE'})).toBe(1);expect(previewRuleMatches(rows,{pattern:'',sign:'ALL'})).toBe(0);});
});
describe('Insight denominators and canonical allocation accounting',()=>{
 it('separates bank/card accounts and excludes nonoperating/suggested/refunds from spend percentages',()=>{
  const expense=movement('expense',{monto:-100},{monto:-100});
  expense.allocations=[{...expense.allocations[0],monto:-40},{...expense.allocations[0],id:'second',monto:-60,category_id:'other',category:{name:'Other'},counterparty_id:'other',counterparty:{name:'Other'}}];
  const rows=[expense,movement('loan',{monto:200},{monto:200,economic_type:'FINANCING_INFLOW'}),movement('transfer',{monto:-80},{monto:-80,economic_type:'INTERNAL_TRANSFER'}),movement('transfer2',{monto:80},{monto:80,economic_type:'INTERNAL_TRANSFER'}),movement('suggestion',{monto:-50},{monto:-50,classification_status:'SUGGESTED'}),movement('refund',{monto:10},{monto:10}),movement('card',{monto:-20,source_account_id:'card',source_account:{id:'card',name:'Card',institution:'SABADELL',product_type:'CARD'}},{monto:-20,economic_type:'CARD_SETTLEMENT'})];
  const data=financeInsights(rows);expect(data.metrics.banking).toEqual({count:7,inflows:29000,outflows:25000,net:4000});expect(data.metrics.operatingExpense).toBe(9000);expect(data.operatingOutflow).toBe(10000);expect(data.categories.find(c=>c.id==='cat').percent).toBe(40);expect(data.providers.find(c=>c.id==='other').percent).toBe(60);expect(data.allocationVolume).toBe(54000);expect(data.unresolvedVolume).toBe(5000);expect(data.unresolvedPercent).toBeCloseTo(100*50/540);expect(data.accounts.map(a=>[a.institution,a.product])).toEqual([['BBVA','BANK_ACCOUNT'],['SABADELL','CARD']]);expect(data.metrics.economic.INTERNAL_TRANSFER.net).toBe(0);expect(data.metrics.economic.FINANCING_INFLOW.net).toBe(20000);
 });
 it('handles empty denominators without NaN or guessed interpretation',()=>{const data=financeInsights([]);expect(data.unresolvedPercent).toBe(0);expect(data.categories).toEqual([]);expect(financeInsights([pending()]).metrics.operatingExpense).toBe(-0);});
});
describe('Dense accessible presentation',()=>{
 it('renders literal nowrap actions, category-first one-line cells, and subtle account context',()=>{const html=renderToStaticMarkup(createElement(FinanceMovementRow,{movement:movement('row'),editable:true,onEdit:()=>{},onRule:()=>{},onSplit:()=>{}}));expect(html).toContain('✏️');expect(html).toContain('⚙️');expect(html).toContain('✂️');expect(html).toContain('flex-nowrap');expect(html).not.toContain('Clasificar en fila');expect(html).toContain('Bank A');expect(html).toContain('aria-label="Editar clasificación"');expect(html).toContain('Food');});
 it('uses Spanish transfer states and paired actions',()=>{const html=renderToStaticMarkup(createElement(TransferReview,{candidates:[{id:'pair',source_movement_id:'one',target_movement_id:'two',status:'SUGGESTED',evidence:{dayDistance:1}}],movementMap:new Map(histories.map(m=>[m.id,m])),onClose:()=>{}}));expect(html).toContain('Sugerida');expect(html).not.toContain('SUGGESTED');expect(html).toContain('↔');});
 it('keeps the Finance legacy navigation key but displays Métricas',()=>{const source=readFileSync('src/components/MainLayout.jsx','utf8');expect(source).toContain("tabs: ['Consolidado', 'Resumen', 'Gráficas']");expect(source).toContain("tab === 'Gráficas' ? 'Métricas' : tab");});
});
